// Service worker: caches every app file so the board works offline.
// When you change any file, bump CACHE_VERSION so devices pick up the update.
const CACHE_VERSION = "aac-v4";
// BEGIN FILE LIST (generated by tools/update-cache-list.py: do not edit by hand)
const FILES = [
  "./",
  "index.html",
  "data/core-board.json",
  "data/image-sources.json",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "images/symbols/all.svg",
  "images/symbols/apple.svg",
  "images/symbols/back.svg",
  "images/symbols/ball.svg",
  "images/symbols/banana.svg",
  "images/symbols/bathroom.svg",
  "images/symbols/bed.svg",
  "images/symbols/blocks.svg",
  "images/symbols/book.svg",
  "images/symbols/bubbles.svg",
  "images/symbols/can.svg",
  "images/symbols/car.svg",
  "images/symbols/cheese.svg",
  "images/symbols/chips.svg",
  "images/symbols/cookie.svg",
  "images/symbols/cracker.svg",
  "images/symbols/dad.svg",
  "images/symbols/different.svg",
  "images/symbols/do.svg",
  "images/symbols/drink.svg",
  "images/symbols/drinks.svg",
  "images/symbols/eat.svg",
  "images/symbols/favorites.svg",
  "images/symbols/finished.svg",
  "images/symbols/food.svg",
  "images/symbols/friend.svg",
  "images/symbols/get.svg",
  "images/symbols/go.svg",
  "images/symbols/good.svg",
  "images/symbols/he.svg",
  "images/symbols/help.svg",
  "images/symbols/here.svg",
  "images/symbols/home.svg",
  "images/symbols/i.svg",
  "images/symbols/in.svg",
  "images/symbols/it.svg",
  "images/symbols/juice.svg",
  "images/symbols/like.svg",
  "images/symbols/look.svg",
  "images/symbols/make.svg",
  "images/symbols/milk.svg",
  "images/symbols/mom.svg",
  "images/symbols/more.svg",
  "images/symbols/music.svg",
  "images/symbols/no.svg",
  "images/symbols/not.svg",
  "images/symbols/on.svg",
  "images/symbols/open.svg",
  "images/symbols/outside.svg",
  "images/symbols/park.svg",
  "images/symbols/people.svg",
  "images/symbols/pizza.svg",
  "images/symbols/places.svg",
  "images/symbols/play.svg",
  "images/symbols/put.svg",
  "images/symbols/same.svg",
  "images/symbols/sandwich.svg",
  "images/symbols/school.svg",
  "images/symbols/she.svg",
  "images/symbols/slide.svg",
  "images/symbols/some.svg",
  "images/symbols/stop.svg",
  "images/symbols/swing.svg",
  "images/symbols/tablet.svg",
  "images/symbols/teacher.svg",
  "images/symbols/that.svg",
  "images/symbols/turn.svg",
  "images/symbols/up.svg",
  "images/symbols/want.svg",
  "images/symbols/water.svg",
  "images/symbols/what.svg",
  "images/symbols/when.svg",
  "images/symbols/where.svg",
  "images/symbols/who.svg",
  "images/symbols/why.svg",
  "images/symbols/yes.svg",
  "images/symbols/you.svg",
  "js/adult.js",
  "js/app.js",
  "js/backup.js",
  "js/board.js",
  "js/db.js",
  "js/editor.js",
  "js/events.js",
  "js/hold.js",
  "js/lock.js",
  "js/profiles.js",
  "js/speech.js",
  "js/storage.js",
  "js/ui.js",
  "manifest.webmanifest",
  "styles.css",
];
// END FILE LIST

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE_VERSION).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first. ignoreSearch lets any ?query on the page address match the cached page.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request))
  );
});
