#!/usr/bin/env python3
"""Rewrites the FILES list in sw.js so it contains every app file.

Run this from the project folder whenever you add or remove a file
(a new picture, script, ...):      python3 tools/update-cache-list.py
Then change CACHE_VERSION in sw.js (for example aac-v4 -> aac-v5) so devices
download the new files. Nothing here needs the internet.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = {".git", "tools", "node_modules"}
SKIP_FILES = {"sw.js", "README.md", "CREDITS.md", ".gitignore"}

files = []
for folder, dirs, names in os.walk(ROOT):
    dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and not d.startswith("."))
    for n in sorted(names):
        rel = os.path.relpath(os.path.join(folder, n), ROOT).replace(os.sep, "/")
        if rel not in SKIP_FILES and not n.startswith("."):
            files.append(rel)

# index.html first, then the rest in a stable order
files.sort(key=lambda f: (f != "index.html", f))
lines = ['  "./",'] + [f'  "{f}",' for f in files]
block = "// BEGIN FILE LIST (generated by tools/update-cache-list.py: do not edit by hand)\n" \
        "const FILES = [\n" + "\n".join(lines) + "\n];\n// END FILE LIST"

path = os.path.join(ROOT, "sw.js")
src = open(path, encoding="utf-8").read()
new, n = re.subn(r"// BEGIN FILE LIST.*?// END FILE LIST", lambda m: block, src, flags=re.S)
if n != 1:
    raise SystemExit("Could not find the BEGIN/END FILE LIST markers in sw.js")
open(path, "w", encoding="utf-8").write(new)
print(f"sw.js updated: {len(files)} files listed")
